package com.genealogy.server.dto;

import java.time.LocalDateTime;

public class SheetResponse {
    private Long id;
    private Integer sheetNumber;
    private String sheetType;
    private String layoutData;
    private LocalDateTime autoGeneratedAt;

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public Integer getSheetNumber() { return sheetNumber; }
    public void setSheetNumber(Integer sheetNumber) { this.sheetNumber = sheetNumber; }
    public String getSheetType() { return sheetType; }
    public void setSheetType(String sheetType) { this.sheetType = sheetType; }
    public String getLayoutData() { return layoutData; }
    public void setLayoutData(String layoutData) { this.layoutData = layoutData; }
    public LocalDateTime getAutoGeneratedAt() { return autoGeneratedAt; }
    public void setAutoGeneratedAt(LocalDateTime autoGeneratedAt) { this.autoGeneratedAt = autoGeneratedAt; }
}
