package com.genealogy.server.model;

import jakarta.persistence.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import java.time.LocalDateTime;

@Entity
@Table(name = "book_sheets")
public class BookSheet {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "draft_id", nullable = false)
    private Long draftId;

    @Column(name = "sheet_number", nullable = false)
    private Integer sheetNumber;

    @Column(name = "sheet_type", length = 20)
    private String sheetType = "genealogy";

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "layout_data", columnDefinition = "JSON")
    private String layoutData;

    @Column(name = "auto_generated_at")
    private LocalDateTime autoGeneratedAt;

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public Long getDraftId() { return draftId; }
    public void setDraftId(Long draftId) { this.draftId = draftId; }
    public Integer getSheetNumber() { return sheetNumber; }
    public void setSheetNumber(Integer sheetNumber) { this.sheetNumber = sheetNumber; }
    public String getSheetType() { return sheetType; }
    public void setSheetType(String sheetType) { this.sheetType = sheetType; }
    public String getLayoutData() { return layoutData; }
    public void setLayoutData(String layoutData) { this.layoutData = layoutData; }
    public LocalDateTime getAutoGeneratedAt() { return autoGeneratedAt; }
    public void setAutoGeneratedAt(LocalDateTime autoGeneratedAt) { this.autoGeneratedAt = autoGeneratedAt; }
}
