package com.genealogy.server.service;

import com.genealogy.server.dto.*;
import com.genealogy.server.exception.NotFoundException;
import com.genealogy.server.model.*;
import com.genealogy.server.repository.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class PublishingServiceTest {

    @Mock private BookDraftRepository bookDraftRepository;
    @Mock private BookSheetRepository bookSheetRepository;
    @Mock private BookPersonDetailRepository bookPersonDetailRepository;
    @Mock private SheetElementOverrideRepository sheetElementOverrideRepository;
    @Mock private DraftSyncLogRepository draftSyncLogRepository;
    @Mock private PublicationRepository publicationRepository;
    @Mock private PersonRepository personRepository;

    @InjectMocks private PublishingService publishingService;

    // ---- Helpers ----

    private BookDraft makeDraft(Long id, Long pubId) {
        BookDraft d = new BookDraft();
        d.setId(id);
        d.setPublicationId(pubId);
        d.setTitle("Test Draft");
        d.setSubtitle("sub");
        d.setPreface("preface text");
        d.setEpilogue("epilogue text");
        d.setStyleConfig("{\"font\":\"song\"}");
        d.setStatus("draft");
        d.setVersion(1);
        d.setSnapshotRevision(0L);
        d.setCreatedBy(1L);
        d.setUpdatedBy(1L);
        d.setCreatedAt(LocalDateTime.now());
        d.setUpdatedAt(LocalDateTime.now());
        return d;
    }

    private Publication makePublication(Long id, String title, Long revision) {
        Publication p = new Publication();
        p.setId(id);
        p.setTitle(title);
        p.setRevision(revision);
        return p;
    }

    private BookSheet makeSheet(Long id, Long draftId, int number) {
        BookSheet s = new BookSheet();
        s.setId(id);
        s.setDraftId(draftId);
        s.setSheetNumber(number);
        s.setSheetType("genealogy");
        s.setLayoutData("{\"cols\":12}");
        s.setAutoGeneratedAt(LocalDateTime.now());
        return s;
    }

    private BookPersonDetail makeDetail(Long id, Long draftId, String personId) {
        BookPersonDetail d = new BookPersonDetail();
        d.setId(id);
        d.setDraftId(draftId);
        d.setPersonId(personId);
        d.setBiography("bio");
        d.setInterlinearNotes("notes");
        d.setSealStyle("seal");
        d.setUserModified(false);
        d.setSourceFieldsHash("abc123");
        d.setUpdatedAt(LocalDateTime.now());
        return d;
    }

    private Person makePerson(Long id, Long pubId, String personId, String name) {
        Person p = new Person();
        p.setId(id);
        p.setPublicationId(pubId);
        p.setPersonId(personId);
        p.setName(name);
        return p;
    }

    // ==================== createDraft ====================

    @Test
    void createDraft_savesDraftAndReturnsResponse() {
        Long userId = 1L;
        BookDraftRequest req = new BookDraftRequest();
        req.setPublicationId(10L);
        req.setTitle("My Draft");
        req.setSubtitle("subtitle");
        req.setPreface("pref");
        req.setEpilogue("epi");
        req.setStyleConfig("{\"color\":\"red\"}");

        BookDraft saved = makeDraft(100L, 10L);
        saved.setTitle("My Draft");
        when(bookDraftRepository.save(any(BookDraft.class))).thenReturn(saved);
        // toResponse calls these
        when(bookSheetRepository.countByDraftId(100L)).thenReturn(0L);
        when(publicationRepository.findById(10L)).thenReturn(
                Optional.of(makePublication(10L, "Pub", 5L)));

        BookDraftResponse resp = publishingService.createDraft(userId, req);

        assertNotNull(resp);
        assertEquals(100L, resp.getId());
        assertEquals("My Draft", resp.getTitle());
        assertEquals(10L, resp.getPublicationId());

        ArgumentCaptor<BookDraft> captor = ArgumentCaptor.forClass(BookDraft.class);
        verify(bookDraftRepository).save(captor.capture());
        BookDraft captured = captor.getValue();
        assertEquals("draft", captured.getStatus());
        assertEquals(1, captured.getVersion());
        assertEquals(0L, captured.getSnapshotRevision());
        assertEquals(userId, captured.getCreatedBy());
        assertEquals(userId, captured.getUpdatedBy());
    }

    // ==================== listDrafts ====================

    @Test
    void listDrafts_returnsDraftResponses() {
        BookDraft d1 = makeDraft(1L, 10L);
        BookDraft d2 = makeDraft(2L, 10L);
        when(bookDraftRepository.findByPublicationIdOrderByUpdatedAtDesc(10L))
                .thenReturn(Arrays.asList(d1, d2));
        when(bookSheetRepository.countByDraftId(anyLong())).thenReturn(0L);
        when(publicationRepository.findById(10L)).thenReturn(
                Optional.of(makePublication(10L, "Pub", 1L)));

        List<BookDraftResponse> results = publishingService.listDrafts(10L);

        assertEquals(2, results.size());
        assertEquals(1L, results.get(0).getId());
        assertEquals(2L, results.get(1).getId());
    }

    @Test
    void listDrafts_empty_returnsEmptyList() {
        when(bookDraftRepository.findByPublicationIdOrderByUpdatedAtDesc(10L))
                .thenReturn(Collections.emptyList());

        List<BookDraftResponse> results = publishingService.listDrafts(10L);

        assertTrue(results.isEmpty());
    }

    // ==================== getDraft ====================

    @Test
    void getDraft_existing_returnsResponse() {
        BookDraft draft = makeDraft(1L, 10L);
        when(bookDraftRepository.findById(1L)).thenReturn(Optional.of(draft));
        when(bookSheetRepository.countByDraftId(1L)).thenReturn(3L);
        when(publicationRepository.findById(10L)).thenReturn(
                Optional.of(makePublication(10L, "Pub", 1L)));

        BookDraftResponse resp = publishingService.getDraft(1L);

        assertEquals(1L, resp.getId());
        assertEquals(3, resp.getSheetCount());
        assertEquals("Pub", resp.getPublicationTitle());
    }

    @Test
    void getDraft_notFound_throws() {
        when(bookDraftRepository.findById(99L)).thenReturn(Optional.empty());

        assertThrows(NotFoundException.class, () -> publishingService.getDraft(99L));
    }

    // ==================== updateDraft ====================

    @Test
    void updateDraft_updatesNonNullFields() {
        BookDraft existing = makeDraft(1L, 10L);
        when(bookDraftRepository.findById(1L)).thenReturn(Optional.of(existing));
        when(bookDraftRepository.save(any(BookDraft.class))).thenAnswer(inv -> inv.getArgument(0));
        when(bookSheetRepository.countByDraftId(1L)).thenReturn(0L);
        when(publicationRepository.findById(10L)).thenReturn(
                Optional.of(makePublication(10L, "Pub", 1L)));

        BookDraftRequest req = new BookDraftRequest();
        req.setTitle("Updated Title");
        req.setSubtitle(null); // should not overwrite
        req.setPreface("new preface");
        req.setEpilogue(null);
        req.setStyleConfig(null);

        BookDraftResponse resp = publishingService.updateDraft(1L, 2L, req);

        assertEquals("Updated Title", resp.getTitle());
        assertEquals("new preface", resp.getPreface());

        ArgumentCaptor<BookDraft> captor = ArgumentCaptor.forClass(BookDraft.class);
        verify(bookDraftRepository).save(captor.capture());
        assertEquals(2L, captor.getValue().getUpdatedBy());
        // subtitle should remain unchanged
        assertEquals("sub", captor.getValue().getSubtitle());
    }

    @Test
    void updateDraft_notFound_throws() {
        when(bookDraftRepository.findById(99L)).thenReturn(Optional.empty());

        BookDraftRequest req = new BookDraftRequest();
        assertThrows(NotFoundException.class,
                () -> publishingService.updateDraft(99L, 1L, req));
    }

    // ==================== deleteDraft ====================

    @Test
    void deleteDraft_existing_deletes() {
        BookDraft draft = makeDraft(1L, 10L);
        when(bookDraftRepository.findById(1L)).thenReturn(Optional.of(draft));

        publishingService.deleteDraft(1L);

        verify(bookDraftRepository).delete(draft);
    }

    @Test
    void deleteDraft_notFound_throws() {
        when(bookDraftRepository.findById(99L)).thenReturn(Optional.empty());

        assertThrows(NotFoundException.class, () -> publishingService.deleteDraft(99L));
    }

    // ==================== upsertPersonDetail (new) ====================

    @Test
    void upsertPersonDetail_newDetail_createsAndSaves() {
        BookDraft draft = makeDraft(1L, 10L);
        when(bookDraftRepository.findById(1L)).thenReturn(Optional.of(draft));
        when(bookPersonDetailRepository.findByDraftIdAndPersonId(1L, "p1"))
                .thenReturn(Optional.empty());

        when(bookPersonDetailRepository.save(any(BookPersonDetail.class)))
                .thenAnswer(inv -> inv.getArgument(0));
        when(personRepository.findByPublicationIdAndPersonId(10L, "p1"))
                .thenReturn(Optional.of(makePerson(50L, 10L, "p1", "张三")));

        BookPersonDetailRequest req = new BookPersonDetailRequest();
        req.setPersonId("p1");
        req.setBiography("bio text");
        req.setInterlinearNotes("notes");
        req.setSealStyle("seal");
        req.setUserModified(true);

        BookPersonDetailResponse resp = publishingService.upsertPersonDetail(1L, req);

        assertNotNull(resp);
        assertEquals("p1", resp.getPersonId());
        assertEquals("张三", resp.getPersonName());
        assertEquals("bio text", resp.getBiography());

        ArgumentCaptor<BookPersonDetail> captor = ArgumentCaptor.forClass(BookPersonDetail.class);
        verify(bookPersonDetailRepository).save(captor.capture());
        assertEquals(1L, captor.getValue().getDraftId());
        assertEquals("p1", captor.getValue().getPersonId());
    }

    @Test
    void upsertPersonDetail_existingDetail_updates() {
        BookDraft draft = makeDraft(1L, 10L);
        when(bookDraftRepository.findById(1L)).thenReturn(Optional.of(draft));

        BookPersonDetail existing = makeDetail(100L, 1L, "p1");
        when(bookPersonDetailRepository.findByDraftIdAndPersonId(1L, "p1"))
                .thenReturn(Optional.of(existing));
        when(bookPersonDetailRepository.save(any(BookPersonDetail.class))).thenAnswer(inv -> inv.getArgument(0));
        when(personRepository.findByPublicationIdAndPersonId(10L, "p1"))
                .thenReturn(Optional.of(makePerson(50L, 10L, "p1", "李四")));

        BookPersonDetailRequest req = new BookPersonDetailRequest();
        req.setPersonId("p1");
        req.setBiography("updated bio");
        req.setUserModified(true);

        BookPersonDetailResponse resp = publishingService.upsertPersonDetail(1L, req);

        assertEquals("updated bio", resp.getBiography());
        verify(bookPersonDetailRepository).save(any(BookPersonDetail.class));
    }

    @Test
    void upsertPersonDetail_draftNotFound_throws() {
        when(bookDraftRepository.findById(99L)).thenReturn(Optional.empty());

        BookPersonDetailRequest req = new BookPersonDetailRequest();
        req.setPersonId("p1");
        assertThrows(NotFoundException.class,
                () -> publishingService.upsertPersonDetail(99L, req));
    }

    // ==================== listPersonDetails ====================

    @Test
    void listPersonDetails_returnsDetails() {
        BookDraft draft = makeDraft(1L, 10L);
        when(bookDraftRepository.findById(1L)).thenReturn(Optional.of(draft));

        BookPersonDetail d1 = makeDetail(1L, 1L, "p1");
        BookPersonDetail d2 = makeDetail(2L, 1L, "p2");
        when(bookPersonDetailRepository.findByDraftId(1L)).thenReturn(Arrays.asList(d1, d2));
        when(personRepository.findByPublicationIdAndPersonId(eq(10L), anyString()))
                .thenReturn(Optional.of(makePerson(50L, 10L, "p1", "张三")));

        List<BookPersonDetailResponse> results = publishingService.listPersonDetails(1L);

        assertEquals(2, results.size());
    }

    @Test
    void listPersonDetails_draftNotFound_throws() {
        when(bookDraftRepository.findById(99L)).thenReturn(Optional.empty());

        assertThrows(NotFoundException.class,
                () -> publishingService.listPersonDetails(99L));
    }

    // ==================== getPersonDetail ====================

    @Test
    void getPersonDetail_existing_returnsDetail() {
        BookDraft draft = makeDraft(1L, 10L);
        when(bookDraftRepository.findById(1L)).thenReturn(Optional.of(draft));

        BookPersonDetail detail = makeDetail(100L, 1L, "p1");
        when(bookPersonDetailRepository.findByDraftIdAndPersonId(1L, "p1"))
                .thenReturn(Optional.of(detail));
        when(personRepository.findByPublicationIdAndPersonId(10L, "p1"))
                .thenReturn(Optional.of(makePerson(50L, 10L, "p1", "张三")));

        BookPersonDetailResponse resp = publishingService.getPersonDetail(1L, "p1");

        assertEquals("p1", resp.getPersonId());
        assertEquals("张三", resp.getPersonName());
        assertEquals("bio", resp.getBiography());
    }

    @Test
    void getPersonDetail_detailNotFound_throws() {
        BookDraft draft = makeDraft(1L, 10L);
        when(bookDraftRepository.findById(1L)).thenReturn(Optional.of(draft));
        when(bookPersonDetailRepository.findByDraftIdAndPersonId(1L, "missing"))
                .thenReturn(Optional.empty());

        assertThrows(NotFoundException.class,
                () -> publishingService.getPersonDetail(1L, "missing"));
    }

    // ==================== deletePersonDetail ====================

    @Test
    void deletePersonDetail_deletes() {
        BookDraft draft = makeDraft(1L, 10L);
        when(bookDraftRepository.findById(1L)).thenReturn(Optional.of(draft));

        publishingService.deletePersonDetail(1L, "p1");

        verify(bookPersonDetailRepository).deleteByDraftIdAndPersonId(1L, "p1");
    }

    @Test
    void deletePersonDetail_draftNotFound_throws() {
        when(bookDraftRepository.findById(99L)).thenReturn(Optional.empty());

        assertThrows(NotFoundException.class,
                () -> publishingService.deletePersonDetail(99L, "p1"));
    }

    // ==================== getSyncStatus ====================

    @Test
    void getSyncStatus_withPendingSync_returnsCorrectly() {
        BookDraft draft = makeDraft(1L, 10L);
        draft.setSnapshotRevision(0L);
        when(bookDraftRepository.findById(1L)).thenReturn(Optional.of(draft));

        Publication pub = makePublication(10L, "Pub", 5L);
        when(publicationRepository.findById(10L)).thenReturn(Optional.of(pub));

        DraftSyncLog log = new DraftSyncLog();
        log.setPersonId("p1");
        log.setChangeType("updated");
        log.setAcknowledged(false);
        when(draftSyncLogRepository.findByDraftIdOrderByCreatedAtDesc(1L))
                .thenReturn(Arrays.asList(log));
        when(personRepository.findByPublicationIdAndPersonId(10L, "p1"))
                .thenReturn(Optional.of(makePerson(50L, 10L, "p1", "张三")));

        DraftSyncStatusResponse resp = publishingService.getSyncStatus(1L);

        assertEquals(1L, resp.getDraftId());
        assertEquals(5L, resp.getCurrentRevision());
        assertEquals(0L, resp.getSnapshotRevision());
        assertTrue(resp.isHasPendingSync());
        assertEquals(1, resp.getChanges().size());
        assertEquals("p1", resp.getChanges().get(0).getPersonId());
        assertEquals("张三", resp.getChanges().get(0).getPersonName());
        assertEquals("updated", resp.getChanges().get(0).getChangeType());
        assertFalse(resp.getChanges().get(0).isAcknowledged());
    }

    @Test
    void getSyncStatus_noPendingSync() {
        BookDraft draft = makeDraft(1L, 10L);
        draft.setSnapshotRevision(5L);
        when(bookDraftRepository.findById(1L)).thenReturn(Optional.of(draft));

        Publication pub = makePublication(10L, "Pub", 5L);
        when(publicationRepository.findById(10L)).thenReturn(Optional.of(pub));
        when(draftSyncLogRepository.findByDraftIdOrderByCreatedAtDesc(1L))
                .thenReturn(Collections.emptyList());

        DraftSyncStatusResponse resp = publishingService.getSyncStatus(1L);

        assertFalse(resp.isHasPendingSync());
        assertTrue(resp.getChanges().isEmpty());
    }

    @Test
    void getSyncStatus_draftNotFound_throws() {
        when(bookDraftRepository.findById(99L)).thenReturn(Optional.empty());

        assertThrows(NotFoundException.class,
                () -> publishingService.getSyncStatus(99L));
    }

    @Test
    void getSyncStatus_publicationNotFound_throws() {
        BookDraft draft = makeDraft(1L, 10L);
        when(bookDraftRepository.findById(1L)).thenReturn(Optional.of(draft));
        when(publicationRepository.findById(10L)).thenReturn(Optional.empty());

        assertThrows(NotFoundException.class,
                () -> publishingService.getSyncStatus(1L));
    }

    // ==================== saveSheets ====================

    @Test
    void saveSheets_replacesAndSavesSheets() {
        BookDraft draft = makeDraft(1L, 10L);
        when(bookDraftRepository.findById(1L)).thenReturn(Optional.of(draft));

        SheetSaveRequest req1 = new SheetSaveRequest();
        req1.setSheetNumber(1);
        req1.setSheetType("genealogy");
        req1.setLayoutData("{\"cols\":12}");

        SheetSaveRequest req2 = new SheetSaveRequest();
        req2.setSheetNumber(2);
        req2.setSheetType("index");
        req2.setLayoutData("{\"cols\":6}");

        BookSheet saved1 = makeSheet(100L, 1L, 1);
        saved1.setSheetType("genealogy");
        BookSheet saved2 = makeSheet(101L, 1L, 2);
        saved2.setSheetType("index");
        when(bookSheetRepository.save(any(BookSheet.class)))
                .thenReturn(saved1)
                .thenReturn(saved2);

        List<SheetResponse> results = publishingService.saveSheets(1L, Arrays.asList(req1, req2));

        assertEquals(2, results.size());
        assertEquals("genealogy", results.get(0).getSheetType());
        assertEquals("index", results.get(1).getSheetType());

        // Old sheets should be deleted first
        verify(bookSheetRepository).deleteByDraftId(1L);
        verify(bookSheetRepository, times(2)).save(any(BookSheet.class));
    }

    @Test
    void saveSheets_defaultSheetType_genealogy() {
        BookDraft draft = makeDraft(1L, 10L);
        when(bookDraftRepository.findById(1L)).thenReturn(Optional.of(draft));

        SheetSaveRequest req = new SheetSaveRequest();
        req.setSheetNumber(1);
        req.setSheetType(null); // should default to "genealogy"
        req.setLayoutData("{}");

        BookSheet saved = makeSheet(100L, 1L, 1);
        when(bookSheetRepository.save(any(BookSheet.class))).thenReturn(saved);

        publishingService.saveSheets(1L, Arrays.asList(req));

        ArgumentCaptor<BookSheet> captor = ArgumentCaptor.forClass(BookSheet.class);
        verify(bookSheetRepository).save(captor.capture());
        assertEquals("genealogy", captor.getValue().getSheetType());
    }

    @Test
    void saveSheets_draftNotFound_throws() {
        when(bookDraftRepository.findById(99L)).thenReturn(Optional.empty());

        assertThrows(NotFoundException.class,
                () -> publishingService.saveSheets(99L, Collections.emptyList()));
    }

    // ==================== listSheets ====================

    @Test
    void listSheets_returnsSheets() {
        when(bookDraftRepository.findById(1L)).thenReturn(Optional.of(makeDraft(1L, 10L)));
        BookSheet s1 = makeSheet(1L, 1L, 1);
        BookSheet s2 = makeSheet(2L, 1L, 2);
        when(bookSheetRepository.findByDraftIdOrderBySheetNumberAsc(1L))
                .thenReturn(Arrays.asList(s1, s2));

        List<SheetResponse> results = publishingService.listSheets(1L);

        assertEquals(2, results.size());
        assertEquals(1, results.get(0).getSheetNumber());
        assertEquals(2, results.get(1).getSheetNumber());
    }

    @Test
    void listSheets_draftNotFound_throws() {
        when(bookDraftRepository.findById(99L)).thenReturn(Optional.empty());

        assertThrows(NotFoundException.class,
                () -> publishingService.listSheets(99L));
    }

    // ==================== deleteSheet ====================

    @Test
    void deleteSheet_matchingDraftId_deletes() {
        BookSheet sheet = makeSheet(100L, 1L, 1);
        when(bookSheetRepository.findById(100L)).thenReturn(Optional.of(sheet));

        publishingService.deleteSheet(1L, 100L);

        verify(bookSheetRepository).delete(sheet);
    }

    @Test
    void deleteSheet_mismatchDraftId_throws() {
        BookSheet sheet = makeSheet(100L, 1L, 1);
        when(bookSheetRepository.findById(100L)).thenReturn(Optional.of(sheet));

        assertThrows(NotFoundException.class,
                () -> publishingService.deleteSheet(999L, 100L));
    }

    @Test
    void deleteSheet_sheetNotFound_throws() {
        when(bookSheetRepository.findById(999L)).thenReturn(Optional.empty());

        assertThrows(NotFoundException.class,
                () -> publishingService.deleteSheet(1L, 999L));
    }
}
