<template>
  <div class="print-preview-container">
    <header class="preview-header">
      <div class="header-left">
        <button class="back-btn" @click="goBack">Back</button>
        <h2>Print Preview <span class="badge">Beta</span></h2>
      </div>
      <div class="actions">
        <div class="status-indicator" v-if="isGenerating">Generating PDF...</div>
        <button class="btn btn--primary" @click="generatePdf" :disabled="isGenerating">
          Export PDF
        </button>
      </div>
    </header>

    <main class="preview-layout">
      <aside class="preview-sidebar">
        <section class="sidebar-section">
          <h3>Sections</h3>
          <ul class="page-nav">
            <li :class="{ active: activeSection === 'preface' }" @click="scrollTo('preface')">Preface</li>
            <li :class="{ active: activeSection === 'bios' }" @click="scrollTo('bios')">Biographies</li>
            <li :class="{ active: activeSection === 'tree' }" @click="scrollTo('tree')">Tree</li>
          </ul>
        </section>

        <section class="sidebar-section">
          <h3>Print Settings</h3>
          <div class="control-group">
            <label>Paper</label>
            <select disabled>
              <option>A4</option>
            </select>
          </div>
          <div class="control-group">
            <label>Font Style</label>
            <select v-model="fontStyle">
              <option value="serif">Serif</option>
              <option value="sans">Sans</option>
            </select>
          </div>
        </section>

        <div class="sidebar-info">
          <p>Edits made here only affect this export.</p>
        </div>
      </aside>

      <div class="preview-viewport">
        <div class="a4-page" id="section-preface">
          <div class="page-content">
            <h1 class="page-title" contenteditable="true" @blur="onTitleBlur">{{ editedTitle }}</h1>
            <div class="divider"></div>
            <p class="section-hint">Edit the preface text below.</p>
            <textarea v-model="editedPreface" class="editable-text preface-text"></textarea>
          </div>
          <div class="page-footer">Page 1</div>
        </div>

        <div class="a4-page" id="section-bios" v-if="exportData?.options.includeBios">
          <div class="page-content">
            <h2 class="section-title">Family Biographies</h2>
            <div class="divider"></div>
            <p class="section-hint">Auto-generated from the current publication.</p>
            <textarea v-model="editedBios" class="editable-text bios-text"></textarea>
          </div>
          <div class="page-footer">Page 2</div>
        </div>

        <div class="a4-page a4-page--landscape" id="section-tree">
          <div class="page-content">
            <h2 class="section-title">Tree Preview</h2>
            <div class="divider"></div>
            <div class="tree-preview-container">
              <img v-if="exportData?.base64Image" :src="exportData.base64Image" class="tree-img" />
            </div>
          </div>
          <div class="page-footer">Tree Preview</div>
        </div>
      </div>
    </main>
  </div>
</template>

<script setup lang="ts">
import { inject, onMounted, ref } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { buildAuthHeaders } from '../api/auth'
import type { Person } from '../types/family'
import { useExportState } from '../features/export/useExportState'

const router = useRouter()
const route = useRoute()
const { getExportData } = useExportState()
const context = inject<any>('publication-context')
const pub = context?.pub

const exportData = getExportData()
const isGenerating = ref(false)
const activeSection = ref('preface')
const fontStyle = ref('serif')
const editedTitle = ref('')
const editedPreface = ref('')
const editedBios = ref('')

onMounted(() => {
  if (!exportData) {
    alert('Missing export data. Please restart the export flow.')
    router.replace(`/publications/${route.params.id}`)
    return
  }

  editedTitle.value = pub?.publication?.title || 'Untitled Publication'
  editedPreface.value = `This document was generated by Guiyuan on ${new Date().toLocaleDateString()}.\n\nThis is a complete lineage record for ${editedTitle.value}.`

  if (pub?.publication?.people) {
    const people = Object.values(pub.publication.people) as Person[]
    editedBios.value = people.map((person) => {
      const years = person.birth || person.death ? ` (${person.birth || '?'} - ${person.death || 'Present'})` : ''
      const note = person.note || '暂无传记信息。'
      return `${person.name}${years}\n${note}`
    }).join('\n\n')
  }
})

function goBack() {
  router.replace(`/publications/${route.params.id}`)
}

function scrollTo(id: string) {
  activeSection.value = id
  document.getElementById(`section-${id}`)?.scrollIntoView({ behavior: 'smooth' })
}

function onTitleBlur(event: FocusEvent) {
  const target = event.target as HTMLElement | null
  editedTitle.value = target?.innerText || editedTitle.value
}

async function generatePdf() {
  if (!exportData) return
  isGenerating.value = true

  try {
    const response = await fetch(`/api/publications/${route.params.id}/export/pdf`, {
      method: 'POST',
      headers: buildAuthHeaders({ 'Content-Type': 'application/json' }),
      body: JSON.stringify({
        base64Image: exportData.base64Image,
        svgMarkup: exportData.svgMarkup,
        prefaceText: editedPreface.value,
        biosText: editedBios.value,
        title: editedTitle.value,
      }),
    })

    if (!response.ok) {
      throw new Error('PDF generation failed')
    }

    const blob = await response.blob()
    const url = window.URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `${editedTitle.value}-book.pdf`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    window.URL.revokeObjectURL(url)
  } catch (error) {
    console.error('PDF export failed', error)
    alert('导出PDF失败，后端可能不可用。')
  } finally {
    isGenerating.value = false
  }
}
</script>

<style scoped>
.print-preview-container {
  height: 100vh;
  display: flex;
  flex-direction: column;
  background: #f0f0f0;
  color: #333;
}

.preview-header {
  height: 64px;
  background: #fff;
  border-bottom: 1px solid #ddd;
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0 24px;
}

.header-left,
.actions {
  display: flex;
  align-items: center;
  gap: 16px;
}

.preview-layout {
  flex: 1;
  display: flex;
  overflow: hidden;
}

.preview-sidebar {
  width: 280px;
  background: #fff;
  border-right: 1px solid #ddd;
  padding: 24px;
  display: flex;
  flex-direction: column;
  gap: 24px;
}

.page-nav {
  list-style: none;
  padding: 0;
  margin: 0;
}

.page-nav li {
  padding: 10px 12px;
  border-radius: 8px;
  cursor: pointer;
}

.page-nav li.active {
  background: #a96e35;
  color: #fff;
}

.preview-viewport {
  flex: 1;
  overflow-y: auto;
  padding: 40px;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 40px;
}

.a4-page {
  background: #fff;
  width: 210mm;
  min-height: 297mm;
  padding: 20mm;
  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);
  display: flex;
  flex-direction: column;
}

.a4-page--landscape {
  width: 297mm;
  min-height: 210mm;
}

.page-content {
  flex: 1;
}

.page-title,
.section-title {
  font-family: 'Noto Serif SC', serif;
}

.divider {
  height: 2px;
  background: #333;
  margin: 1rem 0 1.5rem;
}

.editable-text {
  width: 100%;
  border: 1px solid #ddd;
  background: #fff;
  resize: none;
  padding: 12px;
  line-height: 1.6;
}

.preface-text {
  min-height: 320px;
}

.bios-text {
  min-height: 480px;
}

.tree-preview-container {
  border: 1px solid #eee;
}

.tree-img {
  width: 100%;
  display: block;
}

.page-footer {
  text-align: center;
  color: #777;
  margin-top: 16px;
}

.btn {
  padding: 10px 20px;
  border-radius: 8px;
  border: none;
  cursor: pointer;
}

.btn--primary {
  background: #a96e35;
  color: #fff;
}
</style>
